// <auto-generated />
using System;
using LotoWinRepositorio;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LotoWinRepositorio.Migrations
{
    [DbContext(typeof(LotoWinContext))]
    [Migration("20201031174834_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("LotoWinDominio.Aposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concurso")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAposta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataConcurso")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Apostas");
                });

            modelBuilder.Entity("LotoWinDominio.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApostaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Premiado")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApostaId");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("LotoWinDominio.Numero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JogoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.ToTable("Numeros");
                });

            modelBuilder.Entity("LotoWinDominio.Jogo", b =>
                {
                    b.HasOne("LotoWinDominio.Aposta", null)
                        .WithMany("Jogos")
                        .HasForeignKey("ApostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LotoWinDominio.Numero", b =>
                {
                    b.HasOne("LotoWinDominio.Jogo", null)
                        .WithMany("Numeros")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
